"use client";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header/Header";
import Footer from "@/components/Layout/Footer/Footer";
import ReduxProvider from "@/redux/reduxProvider";
import { usePathname, useRouter } from "next/navigation";
import { ConfigProvider } from "antd";
import { IoIosChatbubbles } from "react-icons/io";

const poppin = Poppins({ subsets: ["latin"], weight: ["400", "600", "500"] });

// export const metadata = {
//   title: "Tredella",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const router = useRouter();
  const notShowingHeaderPath = ["/login", "/register", "/forgotPassword"];
  return (
    <html lang="en">
      <head>
        <title>Tredella</title>
      </head>
      <body className={poppin.className}>
        <ConfigProvider theme={{ token: { colorPrimary: "#B30015" } }}>
          <ReduxProvider>
            {!notShowingHeaderPath.includes(pathname) && <Header />}
            {children}
            {!notShowingHeaderPath.includes(pathname) && <Footer />}
          </ReduxProvider>
        </ConfigProvider>
        <div
          className="relative cursor-pointer"
          onClick={() => router.push("/chat")}
        >
          <div className="fixed bg-primary h-[50px] w-[50px] rounded-full bottom-3 right-3 flex items-center justify-center">
            <IoIosChatbubbles size={35} fill="white" />
          </div>
        </div>
      </body>
    </html>
  );
}
