import MainWrapper from "@/components/common/wrappers/main-wrapper";
import MUIThemeProvider from "@/components/layout/provider/mui-theme-provider";
import "./globals.css";

export const metadata = {
  title: "Tradella",
  description: "Generated by ECommerce",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        {/* Set crossOrigin to a valid string value */}
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body
        style={{
          backgroundColor: "rgba(236, 240, 244, 1)",
          padding: "0px !important",
        }}
      >
        <MUIThemeProvider>
          <MainWrapper>{children}</MainWrapper>
        </MUIThemeProvider>
      </body>
    </html>
  );
}
